dist: bionic
language: python
python:
- "3.8"
before_install:
- sudo apt-get -y install libsystemd-dev
addons:
  apt:
    update: true
install:
  - pip install -r requirements.txt
script:
  - python -m pytest